//action

const TRAVELPEDIA_ACTIONS = {
  ADD_IMAGE: 'ADD_IMAGE',
  ADD_TITLE: 'ADD_TITLE',
  ADD_SUMMARY: 'ADD_SUMMARY',
  ADD_TO_CURRENT: 'ADD_TO_CURRENT',
  ADD_TO_HISTORY: 'ADD_TO_HISTORY'
}

export default TRAVELPEDIA_ACTIONS;

